// <auto-generated />
using DbFirstEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbFirstEF.Migrations
{
    [DbContext(typeof(NewLocalDbContext))]
    [Migration("20241014054038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbFirstEF.Models.CoachProfile", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachId"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoachId");

                    b.ToTable("CoachProfiles");

                    b.HasData(
                        new
                        {
                            CoachId = 1,
                            Biography = "Biography for Coach 1"
                        },
                        new
                        {
                            CoachId = 2,
                            Biography = "Biography for Coach 2"
                        },
                        new
                        {
                            CoachId = 3,
                            Biography = "Biography for Coach 3"
                        },
                        new
                        {
                            CoachId = 20,
                            Biography = "Biography for Coach 20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
