// <auto-generated />
using DbFirstEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbFirstEF.Migrations
{
    [DbContext(typeof(NewLocalDbContext))]
    partial class NewLocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbFirstEF.Models.CoachProfile", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachId"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoachId");

                    b.ToTable("CoachProfiles");

                    b.HasData(
                        new
                        {
                            CoachId = 1,
                            Biography = "Biography for Coach 1"
                        },
                        new
                        {
                            CoachId = 2,
                            Biography = "Biography for Coach 2"
                        },
                        new
                        {
                            CoachId = 3,
                            Biography = "Biography for Coach 3"
                        },
                        new
                        {
                            CoachId = 4,
                            Biography = "Biography for Coach 4"
                        },
                        new
                        {
                            CoachId = 5,
                            Biography = "Biography for Coach 5"
                        },
                        new
                        {
                            CoachId = 6,
                            Biography = "Biography for Coach 6"
                        },
                        new
                        {
                            CoachId = 7,
                            Biography = "Biography for Coach 7"
                        },
                        new
                        {
                            CoachId = 8,
                            Biography = "Biography for Coach 8"
                        },
                        new
                        {
                            CoachId = 9,
                            Biography = "Biography for Coach 9"
                        },
                        new
                        {
                            CoachId = 10,
                            Biography = "Biography for Coach 10"
                        },
                        new
                        {
                            CoachId = 11,
                            Biography = "Biography for Coach 11"
                        },
                        new
                        {
                            CoachId = 12,
                            Biography = "Biography for Coach 12"
                        },
                        new
                        {
                            CoachId = 13,
                            Biography = "Biography for Coach 13"
                        },
                        new
                        {
                            CoachId = 14,
                            Biography = "Biography for Coach 14"
                        },
                        new
                        {
                            CoachId = 15,
                            Biography = "Biography for Coach 15"
                        },
                        new
                        {
                            CoachId = 16,
                            Biography = "Biography for Coach 16"
                        },
                        new
                        {
                            CoachId = 17,
                            Biography = "Biography for Coach 17"
                        },
                        new
                        {
                            CoachId = 18,
                            Biography = "Biography for Coach 18"
                        },
                        new
                        {
                            CoachId = 19,
                            Biography = "Biography for Coach 19"
                        },
                        new
                        {
                            CoachId = 20,
                            Biography = "Biography for Coach 20"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
