// <auto-generated />
using System;
using DbFirstEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbFirstEF.Migrations.NewLocalDbContext1Migrations
{
    [DbContext(typeof(NewLocalDbContext1))]
    [Migration("20241021142349_SeedUsersForNewLocalDbContext1")]
    partial class SeedUsersForNewLocalDbContext1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbFirstEF.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "43/21 New York Ave",
                            DateOfBirth = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "trump@gmail.com",
                            FirstName = "Donald",
                            LastName = "Trump",
                            Password = "trump",
                            PhoneNumber = "123456789",
                            Role = "Coach"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "456 Elm St",
                            DateOfBirth = new DateTime(1985, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "password2",
                            PhoneNumber = "555-5678",
                            Role = "Coach"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "789 Oak St",
                            DateOfBirth = new DateTime(1978, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sam@example.com",
                            FirstName = "Sam",
                            LastName = "Wilson",
                            Password = "password3",
                            PhoneNumber = "555-9101",
                            Role = "Member"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
